package test

import (
	"testing"

	"gorm.io/gorm"
)

func createPreKeeperInstanceSchema(t *testing.T, db *gorm.DB, includeRanking bool) {
	t.Helper()
	statements := []string{
		`CREATE TABLE redis_usage_inboxes (id INTEGER PRIMARY KEY, source TEXT NOT NULL, message_hash TEXT NOT NULL, raw_message TEXT NOT NULL, status TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, last_error TEXT, usage_event_key TEXT, popped_at DATETIME NOT NULL, processed_at DATETIME, created_at DATETIME, updated_at DATETIME)`,
		`CREATE TABLE usage_events (id INTEGER PRIMARY KEY, event_key TEXT, api_group_key TEXT, provider TEXT, endpoint TEXT, auth_type TEXT, request_id TEXT, client_ip TEXT, x_forwarded_for TEXT, user_agent TEXT, model TEXT, model_alias TEXT, reasoning_effort TEXT NOT NULL DEFAULT '', service_tier TEXT NOT NULL DEFAULT '', response_service_tier TEXT NOT NULL DEFAULT '', executor_type TEXT NOT NULL DEFAULT '', timestamp DATETIME, source TEXT, auth_index TEXT, failed NUMERIC, generate NUMERIC NOT NULL DEFAULT 1, latency_ms INTEGER, ttft_ms INTEGER, input_tokens INTEGER, output_tokens INTEGER, reasoning_tokens INTEGER, cached_tokens INTEGER, cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER, created_at DATETIME)`,
		`CREATE TABLE usage_events_archive (id INTEGER PRIMARY KEY, event_key TEXT, api_group_key TEXT, provider TEXT, endpoint TEXT, auth_type TEXT, request_id TEXT, client_ip TEXT, x_forwarded_for TEXT, user_agent TEXT, model TEXT, model_alias TEXT, reasoning_effort TEXT NOT NULL DEFAULT '', service_tier TEXT NOT NULL DEFAULT '', response_service_tier TEXT NOT NULL DEFAULT '', executor_type TEXT NOT NULL DEFAULT '', timestamp DATETIME, source TEXT, auth_index TEXT, failed NUMERIC, generate NUMERIC NOT NULL DEFAULT 1, latency_ms INTEGER, ttft_ms INTEGER, input_tokens INTEGER, output_tokens INTEGER, reasoning_tokens INTEGER, cached_tokens INTEGER, cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER, created_at DATETIME)`,
		`CREATE TABLE usage_identities (id INTEGER PRIMARY KEY, name TEXT, alias TEXT, auth_type INTEGER, auth_type_name TEXT, identity TEXT, type TEXT, provider TEXT, lookup_key TEXT, prefix TEXT, base_url TEXT, file_name TEXT, file_path TEXT, priority INTEGER, disabled NUMERIC, note TEXT, account_id TEXT, project_id TEXT, xai_user_id TEXT, active_start DATETIME, active_until DATETIME, plan_type TEXT, total_requests INTEGER, success_count INTEGER, failure_count INTEGER, input_tokens INTEGER, output_tokens INTEGER, reasoning_tokens INTEGER, cached_tokens INTEGER, cache_read_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER, last_aggregated_usage_event_id INTEGER, first_used_at DATETIME, last_used_at DATETIME, stats_updated_at DATETIME, is_deleted NUMERIC, created_at DATETIME, updated_at DATETIME, deleted_at DATETIME)`,
		`CREATE UNIQUE INDEX uniq_usage_identities_type_identity ON usage_identities(auth_type, identity)`,
		`CREATE TABLE cpa_api_keys (id INTEGER PRIMARY KEY, api_key TEXT, display_key TEXT, key_alias TEXT, is_deleted NUMERIC, last_synced_at DATETIME, created_at DATETIME, updated_at DATETIME)`,
		`CREATE UNIQUE INDEX uniq_cpa_api_keys_api_key ON cpa_api_keys(api_key)`,
		`CREATE TABLE usage_overview_hourly_stats (id INTEGER PRIMARY KEY, bucket_start DATETIME NOT NULL, api_group_key TEXT NOT NULL, model TEXT NOT NULL, auth_index TEXT NOT NULL DEFAULT '', model_alias TEXT NOT NULL DEFAULT '', service_tier TEXT NOT NULL DEFAULT '', response_service_tier TEXT NOT NULL DEFAULT '', reasoning_effort TEXT NOT NULL DEFAULT '', endpoint TEXT NOT NULL DEFAULT '', executor_type TEXT NOT NULL DEFAULT '', request_count INTEGER NOT NULL DEFAULT 0, success_count INTEGER NOT NULL DEFAULT 0, failure_count INTEGER NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, reasoning_tokens INTEGER NOT NULL DEFAULT 0, cached_tokens INTEGER NOT NULL DEFAULT 0, cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
		`CREATE UNIQUE INDEX uniq_usage_overview_hourly_stats_dimensions ON usage_overview_hourly_stats(bucket_start, api_group_key, model, auth_index, model_alias, service_tier, response_service_tier, reasoning_effort, endpoint, executor_type)`,
		`CREATE TABLE usage_overview_daily_stats (id INTEGER PRIMARY KEY, bucket_start DATETIME NOT NULL, api_group_key TEXT NOT NULL, model TEXT NOT NULL, auth_index TEXT NOT NULL DEFAULT '', model_alias TEXT NOT NULL DEFAULT '', service_tier TEXT NOT NULL DEFAULT '', response_service_tier TEXT NOT NULL DEFAULT '', reasoning_effort TEXT NOT NULL DEFAULT '', endpoint TEXT NOT NULL DEFAULT '', executor_type TEXT NOT NULL DEFAULT '', request_count INTEGER NOT NULL DEFAULT 0, success_count INTEGER NOT NULL DEFAULT 0, failure_count INTEGER NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, reasoning_tokens INTEGER NOT NULL DEFAULT 0, cached_tokens INTEGER NOT NULL DEFAULT 0, cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
		`CREATE UNIQUE INDEX uniq_usage_overview_daily_stats_dimensions ON usage_overview_daily_stats(bucket_start, api_group_key, model, auth_index, model_alias, service_tier, response_service_tier, reasoning_effort, endpoint, executor_type)`,
		`CREATE TABLE usage_activity_stats (id INTEGER PRIMARY KEY, grain TEXT NOT NULL, bucket_start DATETIME NOT NULL, bucket_end DATETIME NOT NULL, api_group_key TEXT NOT NULL, success_count INTEGER NOT NULL DEFAULT 0, failure_count INTEGER NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0, output_tokens INTEGER NOT NULL DEFAULT 0, reasoning_tokens INTEGER NOT NULL DEFAULT 0, cache_read_tokens INTEGER NOT NULL DEFAULT 0, cache_creation_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER NOT NULL DEFAULT 0, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
		`CREATE UNIQUE INDEX uniq_usage_activity_stats_grain_start_api ON usage_activity_stats(grain, bucket_start, api_group_key)`,
		`CREATE TABLE usage_latency_stats (id INTEGER PRIMARY KEY, bucket_type TEXT NOT NULL, bucket_start DATETIME NOT NULL, api_group_key TEXT NOT NULL, sample_count INTEGER NOT NULL DEFAULT 0, max_ttft_ms INTEGER NOT NULL DEFAULT 0, max_latency_ms INTEGER NOT NULL DEFAULT 0, format_version INTEGER NOT NULL DEFAULT 1, ttft_sketch BLOB NOT NULL, latency_sketch BLOB NOT NULL, sample_points BLOB NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
		`CREATE UNIQUE INDEX uniq_usage_latency_stats_bucket_api ON usage_latency_stats(bucket_type, bucket_start, api_group_key)`,
		`CREATE TABLE usage_aggregation_checkpoints (name TEXT PRIMARY KEY, last_aggregated_usage_event_id INTEGER NOT NULL DEFAULT 0, stats_updated_at DATETIME, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL)`,
	}
	if includeRanking {
		statements = append(statements, `CREATE TABLE local_ranking_period_stats (period_kind TEXT NOT NULL, period_key TEXT NOT NULL, api_key_id INTEGER NOT NULL, request_count INTEGER NOT NULL DEFAULT 0, success_count INTEGER NOT NULL DEFAULT 0, failure_count INTEGER NOT NULL DEFAULT 0, input_tokens INTEGER NOT NULL DEFAULT 0, cache_read_tokens INTEGER NOT NULL DEFAULT 0, total_tokens INTEGER NOT NULL DEFAULT 0, ttft_sum_ms INTEGER NOT NULL DEFAULT 0, ttft_sample_count INTEGER NOT NULL DEFAULT 0, latency_sum_ms INTEGER NOT NULL DEFAULT 0, latency_sample_count INTEGER NOT NULL DEFAULT 0, peak_5m_request_count INTEGER NOT NULL DEFAULT 0, peak_5m_total_tokens INTEGER NOT NULL DEFAULT 0, updated_at DATETIME NOT NULL, PRIMARY KEY(period_kind, period_key, api_key_id))`)
	}
	for _, statement := range statements {
		if err := db.Exec(statement).Error; err != nil {
			t.Fatalf("create pre-keeper-instance schema: %v\nSQL: %s", err, statement)
		}
	}
}
